/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import component.OrderItem_forUIDatMon;
import entity.ChiTietHoaDon;
import entity.Mon;
import icon.FontAwesome;
import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import jiconfont.swing.IconFontSwing;
import raven.toast.Notifications;
import static utils.AppUtils.*;

/**
 *
 * @author dmx
 */
public class Form_GhiChu extends javax.swing.JPanel {

    /**
     * Creates new form Form_HuyMon
     */
    private JFrame main;
    private OrderItem_forUIDatMon parent;
    private Mon monHuy;
    private int Soluong;

    public Form_GhiChu(JFrame frame, OrderItem_forUIDatMon parent) {
        initComponents();
        this.main = frame;
        this.parent = parent;
        this.setBackground(new Color(0, 0, 0, 0.7f));
        IconFontSwing.register(FontAwesome.getIconFont());
        btnHelp.setIcon(IconFontSwing.buildIcon(FontAwesome.QUESTION, 20, Color.WHITE));
        btnClose.setIcon(IconFontSwing.buildIcon(FontAwesome.WINDOW_CLOSE, 20, Color.WHITE));
        plus.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS, 20, Color.WHITE));
        minus.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS, 20, Color.WHITE));
        Notifications.getInstance().setJFrame(frame);
        FlatIntelliJLaf.setup();
        preLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelRound1 = new component.PanelRound();
        panelRound2 = new component.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnHelp = new component.MyButton();
        btnClose = new component.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BoxLyDo = new javax.swing.JComboBox<>();
        panelRound3 = new component.PanelRound();
        myButton3 = new component.MyButton();
        myButton4 = new component.MyButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        soLuog = new javax.swing.JTextField();
        plus = new javax.swing.JLabel();
        minus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelRound1.setBackground(new java.awt.Color(83, 86, 99));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        panelRound2.setBackground(new java.awt.Color(31, 29, 43));
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);

        jLabel1.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ghi Chú");

        btnHelp.setBackground(new java.awt.Color(31, 29, 43));
        btnHelp.setColor(new java.awt.Color(31, 29, 43));
        btnHelp.setColorClick(new java.awt.Color(31, 29, 43));
        btnHelp.setColorOver(new java.awt.Color(31, 29, 43));
        btnHelp.setRadius(60);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(31, 29, 43));
        btnClose.setColor(new java.awt.Color(31, 29, 43));
        btnClose.setColorClick(new java.awt.Color(31, 29, 43));
        btnClose.setColorOver(new java.awt.Color(31, 29, 43));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnClose.setRadius(60);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jLabel2.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vui lòng điền ghi chú ?");

        jLabel3.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ghi Chú");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("*");

        BoxLyDo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BoxLyDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"","Ít Cay","Nhiều Cay","Cay Vừa","Không Đá","Ít Ngọt","Ngọt","Nhiều Đá"}));
        BoxLyDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxLyDoActionPerformed(evt);
            }
        });

        panelRound3.setBackground(new java.awt.Color(31, 29, 43));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);

        myButton3.setBackground(new java.awt.Color(83, 86, 99));
        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setText("CÓ");
        myButton3.setColor(new java.awt.Color(83, 86, 99));
        myButton3.setColorClick(new java.awt.Color(234, 124, 105));
        myButton3.setColorOver(new java.awt.Color(234, 124, 105));
        myButton3.setFont(utils.AppUtils.getFont(14f, _BOLD_));
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        myButton4.setBackground(new java.awt.Color(83, 86, 99));
        myButton4.setForeground(new java.awt.Color(255, 255, 255));
        myButton4.setText("KHÔNG");
        myButton4.setColor(new java.awt.Color(83, 86, 99));
        myButton4.setColorClick(new java.awt.Color(234, 124, 105));
        myButton4.setColorOver(new java.awt.Color(234, 124, 105));
        myButton4.setFont(utils.AppUtils.getFont(14f, _BOLD_));
        myButton4.setRadius(10);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jLabel5.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số Lượng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("*");

        soLuog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soLuog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        soLuog.setText("1");
        soLuog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soLuogKeyReleased(evt);
            }
        });

        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plusMouseExited(evt);
            }
        });

        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minusMouseExited(evt);
            }
        });

        jLabel7.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ghi Chú Nhanh");

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelRound1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel4))
                                .addGroup(panelRound1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel6))))
                        .addGap(26, 26, 26)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(soLuog, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(plus)
                                .addGap(31, 31, 31)
                                .addComponent(minus))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                            .addComponent(BoxLyDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25))))
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(soLuog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(20, 20, 20)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        main.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
        main.dispose();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        List<ChiTietHoaDon> list = parent.getDatMon().getDetails();
        for (ChiTietHoaDon c : list) {
            if (c.getMon().getTenMon().equals(parent.getMon().getTenMon())) {
                if (c.getGhiChu() == null) {
                    c.setGhiChu("");
                }
                c.setGhiChu(c.getGhiChu() + txtGhiChu.getText());
            }
        }
        parent.getDatMon().setDetails(list);
        main.dispose();
        Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1500, "Thay đổi ghi chú thành công, cất và thêm món để lưu lại tiến trình !");
    }//GEN-LAST:event_myButton3ActionPerformed

    private void BoxLyDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxLyDoActionPerformed
        // TODO add your handling code here:
        if (!parent.getType_orderItem().equals("PRELOAD")){
            txtGhiChu.setText(" " + soLuog.getText() + " "+parent.getMon().getDonVi()+" " + BoxLyDo.getSelectedItem().toString());
        }
        else{
            BoxLyDo.setEditable(false);
            BoxLyDo.setSelectedIndex(0);
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Không được thay đổi ghi chú cho món đã đặt !");
        }
    }//GEN-LAST:event_BoxLyDoActionPerformed

    private void soLuogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soLuogKeyReleased
        // TODO add your handling code here:
        if (!parent.getType_orderItem().equals("PRELOAD")) {
            try {
                Soluong = Integer.parseInt(soLuog.getText());
                if (Soluong == 0) {
                    soLuog.setText("1");
                    Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Số Lượng ghi chú phải lớn hơn 0 !");
                }
                if (Soluong > parent.getSoLuong()) {
                    soLuog.setText(Integer.toString(parent.getSoLuong()));
                    Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Số Lượng ghi chú không được lớn hơn số lượng đặt !");
                }
                txtGhiChu.setText(" " + soLuog.getText() + " "+parent.getMon().getDonVi()+" " + BoxLyDo.getSelectedItem().toString());
            } catch (Exception e) {
                soLuog.setText("1");
                soLuog.requestFocus();
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Số Lượng nhập vào phải là số");
            }
        }
        else{
            soLuog.setText("1");
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Không được thay đổi ghi chú cho món đã đặt !");
        }

    }//GEN-LAST:event_soLuogKeyReleased

    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked
        // TODO add your handling code here:
        if (!parent.getType_orderItem().equals("PRELOAD")) {
            plus.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS, 20, new Color(234, 124, 105)));
            int quantity = Integer.parseInt(soLuog.getText().trim());
            quantity++;
            soLuog.setText(Integer.toString(quantity));
            if (quantity > parent.getSoLuong()) {
                soLuog.setText(Integer.toString(parent.getSoLuong()));
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Số Lượng ghi chú không được lớn hơn số lượng đặt !");
            }
            txtGhiChu.setText(" " + soLuog.getText() + " "+parent.getMon().getDonVi()+" " + BoxLyDo.getSelectedItem().toString());
        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Không được thay đổi ghi chú cho món đã đặt !");
        }

    }//GEN-LAST:event_plusMouseClicked

    private void plusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseEntered
        // TODO add your handling code here:
        plus.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS, 20, new Color(234, 124, 105)));
    }//GEN-LAST:event_plusMouseEntered

    private void plusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseExited
        // TODO add your handling code here:
        plus.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS, 20, Color.WHITE));
    }//GEN-LAST:event_plusMouseExited

    private void minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseClicked
        // TODO add your handling code here:
        minus.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS, 20, new Color(234, 124, 105)));
        if (!parent.getType_orderItem().equals("PRELOAD")) {
            int quantity = Integer.parseInt(soLuog.getText().trim());
            quantity--;
            if (quantity < 1) {
                quantity = 1;
            }
            soLuog.setText(Integer.toString(quantity));
            txtGhiChu.setText(" " + soLuog.getText() + " "+parent.getMon().getDonVi()+" " + BoxLyDo.getSelectedItem().toString());
        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Không được thay đổi ghi chú cho món đã đặt !");
        }

    }//GEN-LAST:event_minusMouseClicked

    private void minusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseEntered
        // TODO add your handling code here:
        minus.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS, 20, new Color(234, 124, 105)));
    }//GEN-LAST:event_minusMouseEntered

    private void minusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseExited
        // TODO add your handling code here:
        minus.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS, 20, Color.WHITE));
    }//GEN-LAST:event_minusMouseExited
    private void preLoad() {
        List<ChiTietHoaDon> list = parent.getDatMon().getDetails();
        for (ChiTietHoaDon c : list) {
            if (parent.getType_orderItem().equals("PRELOAD")) {
                if (c.getMon().getTenMon().equals(parent.getMon().getTenMon())) {
                    if (c.getGhiChu() == null) {
                        txtGhiChu.setText("");
                    } else {
                        txtGhiChu.setText(c.getGhiChu());
                    }
                    txtGhiChu.setEditable(false);
                }
            }
        }
        if(parent.getType_orderItem().equals("PRELOAD")){
            myButton3.setVisible(false);
            myButton4.setText("ĐÓNG");
            jLabel2.setText("Xem Lại Ghi Chú");
            if(!txtGhiChu.getText().equals("")){
                soLuog.setText(txtGhiChu.getText().substring(1, 2));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxLyDo;
    private component.MyButton btnClose;
    private component.MyButton btnHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel minus;
    private component.MyButton myButton3;
    private component.MyButton myButton4;
    private component.PanelRound panelRound1;
    private component.PanelRound panelRound2;
    private component.PanelRound panelRound3;
    private javax.swing.JLabel plus;
    private javax.swing.JTextField soLuog;
    private javax.swing.JTextArea txtGhiChu;
    // End of variables declaration//GEN-END:variables
}
