/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import dao.IBanDAO;
import dao.IChiTietHoaDonDAO;
import dao.IHoaDonDAO;
import dao.IMonDAO;
import dao.ITheThanhVienDAO;
import entity.HoaDon;
import entity.TheThanhVien;
import icon.FontAwesome;
import java.awt.Color;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import jiconfont.swing.IconFontSwing;
import raven.toast.Notifications;
import static utils.AppUtils.*;

/**
 *
 * @author Laptop
 */
public class Form_ThuTien extends javax.swing.JPanel {

    /**
     * Creates new form Form_ThuTien
     */
    private JFrame jFrame;
    private double total;
    private DecimalFormat tien_format = new DecimalFormat("###,### VNĐ");
    private DecimalFormat formatNotVND = new DecimalFormat("###,###");
    private double btnTotal = 0;
//  NDK  Tạo list để lưu các btn
    private List<JButton> moneyDenominations = new ArrayList<>();
    private List<JButton> moneySuggestions = new ArrayList<>();
    private IHoaDonDAO hoaDonDAO = HOADONDAO;
    private IChiTietHoaDonDAO chiTietHoaDonDAO = CHITIETHOADONDAO;
    private ITheThanhVienDAO theThanhVienDAO = THETHANHVIENDAO;
    private IMonDAO monDAO = MONDAO;
    private IBanDAO banDAO = BANDAO;
    private HoaDon hoaDon;
    private JPanel mainJPanel;
    private TheThanhVien theThanhVien;

    public Form_ThuTien(JFrame jFrame, HoaDon hoaDon)  throws RemoteException{
        initComponents();
        this.jFrame = jFrame;
        this.hoaDon = hoaDon;
        this.setBackground(new Color(0, 0, 0, 0.6f));
        wrapper.setBackground(new Color(0, 0, 0, 0));
        IconFontSwing.register(FontAwesome.getIconFont());
        btnDong.setIcon(IconFontSwing.buildIcon(FontAwesome.CHECK, 20, Color.WHITE));
        btnInVaDong.setIcon(IconFontSwing.buildIcon(FontAwesome.PRINT, 20, Color.WHITE));
        createAndSetEventForButtons();
        Notifications.getInstance().setJFrame(jFrame);
        FlatIntelliJLaf.setup();
    }

    private void createAndSetEventForButtons() {
        moneyDenominations.add(btn500);
        moneyDenominations.add(btn200);
        moneyDenominations.add(btn100);
        moneyDenominations.add(btn50);
        moneyDenominations.add(btn20);
        moneyDenominations.add(btn10);
        moneyDenominations.add(btn5);
        moneyDenominations.add(btn2);
        moneyDenominations.add(btn1);
        for (JButton btn : moneyDenominations) {
            btn.addActionListener(e -> {
                String tien = btn.getText().replace(".", ""); // Loại bỏ dấu phẩy
                double tienKhachDua = Double.parseDouble(tien);
                btnTotal += tienKhachDua;
                onChange(total, btnTotal);
            });
        }
    }

    private void createAndSetEventButtonSuggestions() {
        moneySuggestions.add(suggestion1);
        moneySuggestions.add(suggestion2);
        moneySuggestions.add(suggestion3);
        for (JButton btn : moneySuggestions) {
            btn.addActionListener(e -> {
                String tien = btn.getText().replace(",", ""); // Loại bỏ dấu phẩy
                double tienKhachDua = Double.parseDouble(tien);
                btnTotal = tienKhachDua;
                onChange(total, btnTotal);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new component.PanelRound();
        header = new component.PanelRound();
        title = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        leffContainer = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        panelRound1 = new component.PanelRound();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn500 = new component.MyButton();
        btn200 = new component.MyButton();
        btn100 = new component.MyButton();
        btn50 = new component.MyButton();
        btn20 = new component.MyButton();
        btn10 = new component.MyButton();
        btn5 = new component.MyButton();
        btn2 = new component.MyButton();
        btn1 = new component.MyButton();
        jLabel10 = new javax.swing.JLabel();
        suggestion1 = new component.MyButton();
        suggestion2 = new component.MyButton();
        suggestion3 = new component.MyButton();
        rightContainer = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelTienThu = new javax.swing.JLabel();
        tienPhaiThu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tienPhaiTra = new javax.swing.JLabel();
        footer = new component.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDong = new component.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHuy = new component.MyButton();
        btnInVaDong = new component.MyButton();

        wrapper.setRoundBottomLeft(12);
        wrapper.setRoundBottomRight(12);
        wrapper.setRoundTopLeft(12);
        wrapper.setRoundTopRight(12);

        header.setBackground(new java.awt.Color(31, 29, 43));
        header.setRoundTopLeft(16);
        header.setRoundTopRight(16);

        title.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Thu tiền");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_close.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.setBackground(new java.awt.Color(31, 29, 43));

        leffContainer.setBackground(new java.awt.Color(83, 86, 99));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(31, 29, 43));

        jLabel5.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nhập số tiền khách đưa");

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(8);
        panelRound1.setRoundBottomRight(8);
        panelRound1.setRoundTopLeft(8);
        panelRound1.setRoundTopRight(8);

        txtTienKhachDua.setBackground(new java.awt.Color(255, 255, 255));
        txtTienKhachDua.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        txtTienKhachDua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTienKhachDua.setText("0");
        txtTienKhachDua.setBorder(null);
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTienKhachDua)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nhập tiền theo mệnh giá");

        btn500.setForeground(new java.awt.Color(255, 255, 255));
        btn500.setText("500.000");
        btn500.setColor(new java.awt.Color(31, 29, 43));
        btn500.setColorClick(new java.awt.Color(234, 124, 105));
        btn500.setColorOver(new java.awt.Color(234, 124, 105));
        btn500.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn500.setRadius(8);

        btn200.setForeground(new java.awt.Color(255, 255, 255));
        btn200.setText("200.000");
        btn200.setColor(new java.awt.Color(31, 29, 43));
        btn200.setColorClick(new java.awt.Color(234, 124, 105));
        btn200.setColorOver(new java.awt.Color(234, 124, 105));
        btn200.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn200.setRadius(8);

        btn100.setForeground(new java.awt.Color(255, 255, 255));
        btn100.setText("100.000");
        btn100.setColor(new java.awt.Color(31, 29, 43));
        btn100.setColorClick(new java.awt.Color(234, 124, 105));
        btn100.setColorOver(new java.awt.Color(234, 124, 105));
        btn100.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn100.setRadius(8);

        btn50.setForeground(new java.awt.Color(255, 255, 255));
        btn50.setText("50.000");
        btn50.setColor(new java.awt.Color(31, 29, 43));
        btn50.setColorClick(new java.awt.Color(234, 124, 105));
        btn50.setColorOver(new java.awt.Color(234, 124, 105));
        btn50.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn50.setRadius(8);

        btn20.setForeground(new java.awt.Color(255, 255, 255));
        btn20.setText("20.000");
        btn20.setColor(new java.awt.Color(31, 29, 43));
        btn20.setColorClick(new java.awt.Color(234, 124, 105));
        btn20.setColorOver(new java.awt.Color(234, 124, 105));
        btn20.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn20.setRadius(8);

        btn10.setForeground(new java.awt.Color(255, 255, 255));
        btn10.setText("10.000");
        btn10.setColor(new java.awt.Color(31, 29, 43));
        btn10.setColorClick(new java.awt.Color(234, 124, 105));
        btn10.setColorOver(new java.awt.Color(234, 124, 105));
        btn10.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn10.setRadius(8);

        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5.000");
        btn5.setColor(new java.awt.Color(31, 29, 43));
        btn5.setColorClick(new java.awt.Color(234, 124, 105));
        btn5.setColorOver(new java.awt.Color(234, 124, 105));
        btn5.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn5.setRadius(8);

        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2.000");
        btn2.setColor(new java.awt.Color(31, 29, 43));
        btn2.setColorClick(new java.awt.Color(234, 124, 105));
        btn2.setColorOver(new java.awt.Color(234, 124, 105));
        btn2.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn2.setRadius(8);

        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1.000");
        btn1.setColor(new java.awt.Color(31, 29, 43));
        btn1.setColorClick(new java.awt.Color(234, 124, 105));
        btn1.setColorOver(new java.awt.Color(234, 124, 105));
        btn1.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        btn1.setRadius(8);

        jLabel10.setFont(utils.AppUtils.getFont(14f, _NORMAL_));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gợi ý tiền mặt");

        suggestion1.setBorder(null);
        suggestion1.setForeground(new java.awt.Color(255, 255, 255));
        suggestion1.setText("myButton1");
        suggestion1.setColor(new java.awt.Color(234, 124, 105));
        suggestion1.setColorClick(new java.awt.Color(234, 124, 105));
        suggestion1.setColorOver(new java.awt.Color(234, 124, 105));
        suggestion1.setFocusable(false);
        suggestion1.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        suggestion1.setRadius(8);
        suggestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestion1ActionPerformed(evt);
            }
        });

        suggestion2.setBorder(null);
        suggestion2.setForeground(new java.awt.Color(255, 255, 255));
        suggestion2.setText("myButton1");
        suggestion2.setColor(new java.awt.Color(234, 124, 105));
        suggestion2.setColorClick(new java.awt.Color(234, 124, 105));
        suggestion2.setColorOver(new java.awt.Color(234, 124, 105));
        suggestion2.setFocusable(false);
        suggestion2.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        suggestion2.setRadius(8);

        suggestion3.setBorder(null);
        suggestion3.setForeground(new java.awt.Color(255, 255, 255));
        suggestion3.setText("myButton1");
        suggestion3.setColor(new java.awt.Color(234, 124, 105));
        suggestion3.setColorClick(new java.awt.Color(234, 124, 105));
        suggestion3.setColorOver(new java.awt.Color(234, 124, 105));
        suggestion3.setFocusable(false);
        suggestion3.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        suggestion3.setRadius(8);

        javax.swing.GroupLayout leffContainerLayout = new javax.swing.GroupLayout(leffContainer);
        leffContainer.setLayout(leffContainerLayout);
        leffContainerLayout.setHorizontalGroup(
            leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(leffContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9)
                        .addGroup(leffContainerLayout.createSequentialGroup()
                            .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(leffContainerLayout.createSequentialGroup()
                            .addComponent(btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(leffContainerLayout.createSequentialGroup()
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10)
                        .addGroup(leffContainerLayout.createSequentialGroup()
                            .addComponent(suggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(suggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(suggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );
        leffContainerLayout.setVerticalGroup(
            leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leffContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        rightContainer.setBackground(new java.awt.Color(83, 86, 99));

        jSeparator1.setForeground(new java.awt.Color(31, 29, 43));

        jSeparator3.setForeground(new java.awt.Color(31, 29, 43));

        labelTienThu.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        labelTienThu.setForeground(new java.awt.Color(255, 255, 255));
        labelTienThu.setText("Số tiền còn phải thu");

        tienPhaiThu.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        tienPhaiThu.setForeground(new java.awt.Color(255, 255, 255));
        tienPhaiThu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tienPhaiThu.setText("2.000.000");

        jLabel7.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tiền trả lại khách");

        tienPhaiTra.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        tienPhaiTra.setForeground(new java.awt.Color(255, 255, 255));
        tienPhaiTra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tienPhaiTra.setText("0 VNĐ");

        javax.swing.GroupLayout rightContainerLayout = new javax.swing.GroupLayout(rightContainer);
        rightContainer.setLayout(rightContainerLayout);
        rightContainerLayout.setHorizontalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightContainerLayout.createSequentialGroup()
                        .addComponent(labelTienThu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tienPhaiThu, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightContainerLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tienPhaiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rightContainerLayout.setVerticalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTienThu)
                    .addComponent(tienPhaiThu))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tienPhaiTra))
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(leffContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leffContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        footer.setBackground(new java.awt.Color(31, 29, 43));
        footer.setRoundBottomLeft(16);
        footer.setRoundBottomRight(16);

        jLabel1.setFont(utils.AppUtils.getFont(14f, _ITALIC_));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đóng:");

        jLabel3.setFont(utils.AppUtils.getFont(14f, _ITALIC_));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("In & Đóng:");

        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setText("ĐÓNG");
        btnDong.setColor(new java.awt.Color(83, 86, 99));
        btnDong.setColorClick(new java.awt.Color(234, 124, 105));
        btnDong.setColorOver(new java.awt.Color(234, 124, 105));
        btnDong.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        btnDong.setRadius(8);
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel2.setFont(utils.AppUtils.getFont(14f, _ITALIC_));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALT + N hoặc F8");

        jLabel4.setFont(utils.AppUtils.getFont(14f, _ITALIC_));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ALT + L hoặc F9");

        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY BỎ");
        btnHuy.setColor(new java.awt.Color(83, 86, 99));
        btnHuy.setColorClick(new java.awt.Color(234, 124, 105));
        btnHuy.setColorOver(new java.awt.Color(234, 124, 105));
        btnHuy.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        btnHuy.setRadius(8);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnInVaDong.setForeground(new java.awt.Color(255, 255, 255));
        btnInVaDong.setText("IN & ĐÓNG");
        btnInVaDong.setColor(new java.awt.Color(83, 86, 99));
        btnInVaDong.setColorClick(new java.awt.Color(234, 124, 105));
        btnInVaDong.setColorOver(new java.awt.Color(234, 124, 105));
        btnInVaDong.setFont(utils.AppUtils.getFont(16f, _NORMAL_));
        btnInVaDong.setRadius(8);
        btnInVaDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInVaDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInVaDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInVaDong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                pay();
                return null;
            }

            @Override
            protected void done() {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 1000, "Thanh toán thành công");
                jFrame.setVisible(false);
                jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                utils.AppUtils.setUI(mainJPanel, () -> {
                    try {
                        return new GD_DatBanTaiCho(mainJPanel, NHANVIEN);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Form_ThuTien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    return null;
                });
            }

        };

        worker.execute();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        jFrame.setVisible(false);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnInVaDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInVaDongActionPerformed
        // TODO add your handling code here:
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                pay();
                return null;
            }

            @Override
            protected void done() {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 1000, "Thanh toán và tạo hóa đơn thành công");
                try {
                    createHoaDon();
                } catch (RemoteException ex) {
                    Logger.getLogger(Form_ThuTien.class.getName()).log(Level.SEVERE, null, ex);
                }
                jFrame.setVisible(false);
                jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                utils.AppUtils.setUI(mainJPanel, () -> {
                    try {
                        return new GD_DatBanTaiCho(mainJPanel, NHANVIEN);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Form_ThuTien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    return null;
                });
            }

        };

        worker.execute();

    }//GEN-LAST:event_btnInVaDongActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        jFrame.setVisible(false);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtTienKhachDuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtTienKhachDuaKeyTyped

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!txtTienKhachDua.getText().trim().equals("")) {
            String tien = txtTienKhachDua.getText().replace(",", "");
            double tienKhachDua = Double.parseDouble(tien);
            if (Character.isDigit(c)) {
                txtTienKhachDua.setText(formatNotVND.format(tienKhachDua));
            }
            tienPhaiTra.setText(tien_format.format(tienKhachDua - total));
        } else {
            tienPhaiTra.setText("0 VNĐ");
            btnTotal = 0;
        }
        txtTienKhachDua.requestFocus();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void suggestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suggestion1ActionPerformed

    private void onChange(double total, double btnTotal) {
        if (total - btnTotal < 0) {
            txtTienKhachDua.setText("0");
        } else {
            txtTienKhachDua.setText(formatNotVND.format(total - btnTotal));
        }
        tienPhaiTra.setText(tien_format.format(btnTotal - total));
    }

    void setTienPhaiThu(Double total) {
        this.total = total;
        tienPhaiThu.setText(tien_format.format(total));
        double originalValue = total;
        List<Double> suggestions = getSuggestedAmounts(total);
        for (int i = 0; i < suggestions.size(); i++) {
            moneySuggestions.get(i).setText(formatNotVND.format(suggestions.get(i)));
        }
    }

    public List<Double> getSuggestedAmounts(double originalValue) {
        createAndSetEventButtonSuggestions();
        List<Double> suggestions = new ArrayList<>();
        suggestions.add(Math.ceil(originalValue / 1000) * 1000);
        suggestions.add(Math.ceil(originalValue / 10000) * 10000);
        suggestions.add(Math.ceil(originalValue / 100000) * 100000);
        return suggestions;
    }

    private void createHoaDon() throws RemoteException {
        String tien = tienPhaiTra.getText().replace("VNĐ", "");
        tien = tien.replace(",", "");
        double tienThua = Double.parseDouble(tien);
        hoaDonDAO.createInvoice(hoaDon, total + tienThua, tienThua);
    }
    
    //duccuong1609 : khuyenmai thanh nhieu nhieu voi hoa don roi
    private void pay() throws RemoteException {
        if (theThanhVien != null) {
            double diemTichLuy = theThanhVien.getDiemTich() + ((int) total / 100000);
            if (diemTichLuy >= 100.0) {
                theThanhVien.setLoaiThe(utils.Enum.LoaiTheThanhVien.DONG);
            } else if (diemTichLuy >= 500.0) {
                theThanhVien.setLoaiThe(utils.Enum.LoaiTheThanhVien.BAC);
            } else if (diemTichLuy >= 2000.0) {
                theThanhVien.setLoaiThe(utils.Enum.LoaiTheThanhVien.VANG);
            } else if (diemTichLuy >= 10000.0) {
                System.out.println("VCL dcmm");
                theThanhVien.setLoaiThe(utils.Enum.LoaiTheThanhVien.KIMCUONG);
            }
            // Làm tròn số với hai chữ số thập phân
            theThanhVien.setDiemTich(Math.round(diemTichLuy * 100.0) / 100.0);
            theThanhVienDAO.update(theThanhVien);
        }
//        hoaDon.setKhuyenMai(khuyenMais);
        hoaDon.setTrangThai(utils.Enum.LoaiTrangThaiHoaDon.DA_THANH_TOAN);
        hoaDonDAO.update(hoaDon);
        banDAO.updateStateById(hoaDon.getBan().getMaBan(), utils.Enum.LoaiTrangThai.BAN_TRONG);
    }

    public void setMainJPanel(JPanel jPanel) {
        this.mainJPanel = jPanel;
    }


    public void setTheThanhVien(TheThanhVien theThanhVien) {
        this.theThanhVien = theThanhVien;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btn1;
    private component.MyButton btn10;
    private component.MyButton btn100;
    private component.MyButton btn2;
    private component.MyButton btn20;
    private component.MyButton btn200;
    private component.MyButton btn5;
    private component.MyButton btn50;
    private component.MyButton btn500;
    private component.MyButton btnDong;
    private component.MyButton btnHuy;
    private component.MyButton btnInVaDong;
    private javax.swing.JPanel container;
    private component.PanelRound footer;
    private component.PanelRound header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelTienThu;
    private javax.swing.JPanel leffContainer;
    private component.PanelRound panelRound1;
    private javax.swing.JPanel rightContainer;
    private component.MyButton suggestion1;
    private component.MyButton suggestion2;
    private component.MyButton suggestion3;
    private javax.swing.JLabel tienPhaiThu;
    private javax.swing.JLabel tienPhaiTra;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtTienKhachDua;
    private component.PanelRound wrapper;
    // End of variables declaration//GEN-END:variables

}
