/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import icon.FontAwesome;
import java.awt.Color;
import java.awt.Dimension;
import java.text.DecimalFormat;
import jiconfont.swing.IconFontSwing;
import static utils.AppUtils.*;
/**
 *
 * @author Laptop
 */
public class OrderItem extends javax.swing.JPanel {

    /**
     * Creates new form OrderItem
     */
//    Text or Button
    private String type = "TEXT";
    private DecimalFormat tien_format = new DecimalFormat("###,### VNĐ");
    private String[] data;

    public OrderItem(int width, int index, String[] data) {
        this.data = data;
        initComponents();
        setBackground(index % 2 != 0 ? new Color(83, 86, 99) : new Color(31, 29, 43));
        setPreferredSize(new Dimension(width, 50));
        push(data);
    }

    public void setType(String type) {
        this.type = type;
        push(data);
    }

    public void push(String[] data) {
        tenMon.setText("  " + data[0]);
        soLuong.setText("  " + data[1]);
        donGia.setText(" " + tien_format.format(Double.parseDouble(data[2])));
        setLastItem(data[3]);
    }

    private void setLastItem(String data) {
        if (type.equals("BUTTON")) {
            IconFontSwing.register(FontAwesome.getIconFont());
            thanhTien.setIcon(IconFontSwing.buildIcon(FontAwesome.TRASH, 30, Color.white));
        } else {
            thanhTien.setText(" " + tien_format.format(Double.parseDouble(data)));
        }
    }

//    public OrderItem(int index) {
//        initComponents();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenMon = new javax.swing.JLabel();
        soLuong = new javax.swing.JLabel();
        donGia = new javax.swing.JLabel();
        thanhTien = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        tenMon.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        tenMon.setForeground(new java.awt.Color(255, 255, 255));
        add(tenMon);

        soLuong.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        soLuong.setForeground(new java.awt.Color(255, 255, 255));
        add(soLuong);

        donGia.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        donGia.setForeground(new java.awt.Color(255, 255, 255));
        add(donGia);

        thanhTien.setFont(utils.AppUtils.getFont(16f, _BOLD_));
        thanhTien.setForeground(new java.awt.Color(255, 255, 255));
        thanhTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thanhTienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thanhTienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thanhTienMouseExited(evt);
            }
        });
        add(thanhTien);
    }// </editor-fold>//GEN-END:initComponents

    private void thanhTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thanhTienMouseClicked
        // TODO add your handling code here:
        if (type.equals("BUTTON")) {
//            Handle....
            System.out.println("Handling...");
        }
    }//GEN-LAST:event_thanhTienMouseClicked

    private void thanhTienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thanhTienMouseEntered
        // TODO add your handling code here:
//        thanhTien.setFont(new Font("Jetbrains Mono", Font.BOLD, 20));

        if (type.equals("BUTTON")) {
            IconFontSwing.register(FontAwesome.getIconFont());
            thanhTien.setIcon(IconFontSwing.buildIcon(FontAwesome.TRASH, 30, new Color(234, 124, 105)));
        }
    }//GEN-LAST:event_thanhTienMouseEntered

    private void thanhTienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thanhTienMouseExited
        // TODO add your handling code here:
//        thanhTien.setFont(new Font("Jetbrains Mono", Font.BOLD, 14));
        if (type.equals("BUTTON")) {
            IconFontSwing.register(FontAwesome.getIconFont());
            thanhTien.setIcon(IconFontSwing.buildIcon(FontAwesome.TRASH, 30, Color.white));
        }
    }//GEN-LAST:event_thanhTienMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donGia;
    private javax.swing.JLabel soLuong;
    private javax.swing.JLabel tenMon;
    private javax.swing.JLabel thanhTien;
    // End of variables declaration//GEN-END:variables

}
